# Generated by Django 5.2.14 on 2026-08-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_departmentuser_assigned_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='assigned_entra_group',
            field=models.JSONField(blank=True, default=list, editable=False, null=True),
        ),
    ]
