# Generated by Django 5.2.14 on 2026-08-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_departmentuser_assigned_entra_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentuser',
            name='assigned_entra_group',
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='assigned_entra_groups',
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
