# Generated by Django 5.2.17 on 2026-09-04 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itsystems', '0019_alter_itsystemrecord_disposal_authority'),
        ('organisation', '0011_remove_departmentuser_assigned_entra_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('asset_type', models.CharField(choices=[('UD', 'User Device'), ('S', 'Server'), ('CI', 'Container Image'), ('ND', 'Network Device'), ('WA', 'Web Application'), ('M', 'Misc'), ('U', 'Unknown')], default='U', max_length=2, verbose_name='Asset Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('asset_type_data', models.JSONField(blank=True, default=dict, null=True)),
                ('contacts', models.ManyToManyField(blank=True, help_text='The department user(s) to contact for a technical request', related_name='asset_contact_of', to='organisation.departmentuser', verbose_name='Asset Contacts')),
                ('systems', models.ManyToManyField(blank=True, help_text='IT Systems that use this asset', related_name='related_assets', to='itsystems.itsystemrecord', verbose_name='Associated IT Systems')),
                ('owner', models.ForeignKey(blank=True, help_text='The unit / branch responsible for this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_owner_of', to='assets.assetowner', verbose_name='Asset Owner')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
    ]
