# Generated by Django 5.2.17 on 2026-09-04 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Operating System'),
        ),
        migrations.AddField(
            model_name='asset',
            name='os_version',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_os_version', message='OS version must be formatted as 1-3 integers separated by full stops.', regex='^(?:$|(?:(\\d+)\\.)?(?:(\\d+)\\.)?(\\d+))$')], verbose_name='Operating System Version'),
        ),
    ]
