# Generated by Django 5.2.17 on 2026-09-07 06:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_os_asset_os_version'),
        ('organisation', '0011_remove_departmentuser_assigned_entra_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='First Seen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_seen',
            field=models.DateTimeField(default=None, verbose_name='Last Seen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='contacts',
            field=models.ManyToManyField(blank=True, help_text='The department user(s) to contact for a technical request', related_name='asset_contact_of', to='organisation.departmentuser', verbose_name='Contacts'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os_version',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_os_version', message="Invalid OS Version formatting. Please use format Int[.Int[.Int]], ie; '24.04', '12.6.03', etc).", regex='^(?:$|(?:(\\d+)\\.)?(?:(\\d+)\\.)?(\\d+))$')], verbose_name='OS Version'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The unit / branch responsible for this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_owner_of', to='assets.assetowner', verbose_name='Owner'),
        ),
    ]
