# Generated by Django 5.2.17 on 2026-09-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_first_seen_asset_last_modified_asset_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='aliases',
            field=models.JSONField(blank=True, default=list, editable=False, null=True, verbose_name='Alternate names'),
        ),
    ]
