# Generated by Django 5.2.17 on 2026-09-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_defender_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_tenable_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
