# Generated by Django 5.2.17 on 2026-09-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_asset_defender_data_asset_asset_tenable_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_type_data',
        ),
    ]
