# Generated by Django 5.2.17 on 2026-09-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_remove_asset_asset_type_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tenable_id',
            field=models.CharField(default=None, editable=False, max_length=255, unique=True, verbose_name='tenable_id'),
            preserve_default=False,
        ),
    ]
