# Generated by Django 5.2.17 on 2026-09-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_asset_tenable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tenable_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='tenable_id'),
        ),
    ]
