# Generated by Django 5.2.17 on 2026-09-21 07:11

import assets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_asset_tenable_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Asset Tag',
                'verbose_name_plural': 'Asset Tags',
            },
        ),
        migrations.CreateModel(
            name='AssetTagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Asset Tag Category',
                'verbose_name_plural': 'Asset Tag Categories',
            },
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_defender_data',
            new_name='defender_data',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_tenable_data',
            new_name='tenable_data',
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_assets', to='assets.assettag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='assettag',
            name='category',
            field=models.ForeignKey(default=assets.models.AssetTagCategory.get_default_pk, help_text='Tag Category', on_delete=django.db.models.deletion.CASCADE, related_name='tags_within_category', to='assets.assettagcategory'),
        ),
    ]
