# Generated by Django 5.2.17 on 2026-09-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_assettag_assettagcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettag',
            name='tag_id',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
