# Generated by Django 5.2.17 on 2026-09-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_assettag_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tenable_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='tenable_id'),
        ),
    ]
