# Generated by Django 5.2.17 on 2026-09-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_asset_tenable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Seen'),
        ),
    ]
