# Generated by Django 5.2.17 on 2026-09-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_alter_asset_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettag',
            name='tag_id',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
