# Generated by Django 5.2.17 on 2026-09-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_alter_assettag_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.DeleteModel(
            name='AssetOwner',
        ),
    ]
