# Generated by Django 5.2.17 on 2026-09-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_remove_asset_owner_remove_asset_asset_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tenable Tags', related_name='tagged_assets', to='assets.assettag', verbose_name='Tags'),
        ),
    ]
