# Generated by Django 5.2.17 on 2026-09-29 01:07

import assets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_alter_asset_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assettag',
            options={'verbose_name': 'Tag Value', 'verbose_name_plural': 'Tag Values'},
        ),
        migrations.AlterModelOptions(
            name='assettagcategory',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='assettag',
            name='category',
            field=models.ForeignKey(default=assets.models.AssetTagCategory.get_default_pk, help_text='Tag Category', on_delete=django.db.models.deletion.CASCADE, related_name='tags_values', to='assets.assettagcategory'),
        ),
    ]
