# Generated by Django 5.2.17 on 2026-10-01 00:59

import assets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_alter_assettag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettag',
            name='tag_id',
        ),
        migrations.AlterField(
            model_name='assettag',
            name='category',
            field=models.ForeignKey(default=assets.models.AssetTagCategory.get_default_pk, help_text='Tag Category', on_delete=django.db.models.deletion.CASCADE, related_name='tag_values', to='assets.assettagcategory', verbose_name='Tag Category'),
        ),
        migrations.AddConstraint(
            model_name='assettag',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_tag'),
        ),
    ]
